#!/usr/bin/env node

/**
 * Task 2.1 Integration Test Script
 * Verifies Prisma integration without requiring real Claude API key
 * 
 * Usage: npx ts-node src/test-task-2-1.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function runTest() {
  console.log('\n🧪 Task 2.1 Integration Test\n');
  console.log('Testing: Prisma Job Creation + Update Flow\n');

  try {
    // Test 1: Create a Job (simulating before Claude API call)
    console.log('✓ Test 1: Creating Job record...');
    const job = await prisma.job.create({
      data: {
        userId: 'test-user-123',
        type: 'script',
        status: 'processing',
        progress: 10,
        // projectId is optional (set to null)
      },
    });

    console.log(`  Job created: ${job.id}`);
    console.log(`  Status: ${job.status}`);
    console.log(`  Progress: ${job.progress}%`);

    // Verify Job ID is CUID format (real Prisma ID)
    if (job.id.length > 15) {
      console.log(`  ✅ Real Prisma ID generated (CUID format)\n`);
    } else {
      throw new Error('Invalid Job ID format');
    }

    // Test 2: Update Job (simulating after Claude API call)
    console.log('✓ Test 2: Updating Job with result...');
    const processingTimeMs = Math.floor(Math.random() * 3000) + 1000;

    const updatedJob = await prisma.job.update({
      where: { id: job.id },
      data: {
        status: 'completed',
        progress: 100,
        result: JSON.stringify({
          script:
            '[SCRIPT]\nSCENE 1: The Quest Begins\nFADE IN: A mighty dragon guards a golden chest...\n[END SCRIPT]',
        }),
        processingTimeMs,
        completedAt: new Date(),
      },
    });

    console.log(`  Job updated: ${updatedJob.id}`);
    console.log(`  Status: ${updatedJob.status}`);
    console.log(`  Progress: ${updatedJob.progress}%`);
    console.log(`  Processing time: ${processingTimeMs}ms`);
    console.log(`  Result stored: ${updatedJob.result ? 'Yes' : 'No'}\n`);

    // Test 3: Retrieve Job by ID (simulating GET /job/:id endpoint)
    console.log('✓ Test 3: Retrieving Job from database...');
    const retrievedJob = await prisma.job.findUnique({
      where: { id: job.id },
    });

    if (retrievedJob) {
      console.log(`  Retrieved Job: ${retrievedJob.id}`);
      console.log(`  Final Status: ${retrievedJob.status}`);
      console.log(`  Final Progress: ${retrievedJob.progress}%`);
      console.log(`  User ID (for isolation): ${retrievedJob.userId}\n`);
    }

    // Test 4: Verify user isolation
    console.log('✓ Test 4: Verifying user isolation...');
    const otherUserJob = await prisma.job.findFirst({
      where: {
        id: job.id,
        userId: 'different-user', // Should not find
      },
    });

    if (!otherUserJob) {
      console.log(`  ✅ User isolation verified - other user cannot access job\n`);
    }

    // Summary
    console.log('═══════════════════════════════════════');
    console.log('🎉 All Tests PASSED!\n');
    console.log('Task 2.1 Verification Summary:');
    console.log(
      '  ✅ Job creation with Prisma (before Claude API)',
    );
    console.log('  ✅ Job update with results (after Claude API)');
    console.log('  ✅ Real CUID IDs generated by Prisma');
    console.log('  ✅ Job retrieval by ID');
    console.log('  ✅ User isolation enforced');
    console.log('\nNext Step: Task 2.2 - Add ANTHROPIC_API_KEY and test real endpoint');
    console.log('═══════════════════════════════════════\n');

    // Cleanup: Delete test job
    await prisma.job.delete({
      where: { id: job.id },
    });
    console.log('✓ Test data cleaned up\n');
  } catch (error) {
    console.error('\n❌ Test FAILED:\n');
    console.error(error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

runTest();
